main/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.page_home, name='home'),
    path('price/', views.page_price, name='price'),
    path('assembly/', views.page_assembly, name='assembly'),
    path('vacancies/', views.page_vacancies, name='vacancies'),
    path('profile/', views.page_profile, name='profile'),
    path('filters/<slug:fil_slug>/', views.show_category, name='filters'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pk_club/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pk_club import settings
from main.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounts/', include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Изменения сайта"

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
]

main/models.py
from django.db import models
from django.urls import reverse


class Text_Photo(models.Model):
    about_site = models.TextField(blank=True, default=None)
    image_for_carousel = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True, verbose_name='Фото')
    logo = models.ImageField(upload_to='photos', default=None, blank=True, verbose_name='Фото')
    is_published = models.BooleanField(default=True)

    objects = models.Manager()

    def __str__(self):
        return self.pk

    class Meta:
        verbose_name = 'Тексты и фото'
        verbose_name_plural = 'текст или фото'


class Price(models.Model):
    computer = models.CharField(blank=True, default=None, max_length=100, verbose_name="компьютеры")
    playstation = models.CharField(blank=True, default=None, max_length=100, verbose_name="плейстейшен")

    objects = models.Manager()

    def __str__(self):
        return self.pk

    class Meta:
        verbose_name = 'Цена'
        verbose_name_plural = 'Цены'


class Assembly(models.Model):
    vip = models.CharField(blank=True, default=None, max_length=100)
    main = models.CharField(blank=True, default=None, max_length=100)
    ps = models.CharField(blank=True, default=None, max_length=100)

    objects = models.Manager()

    def __str__(self):
        return self.pk

    class Meta:
        verbose_name = 'Сборка пк'
        verbose_name_plural = 'Сборки пк'


class Vacancies(models.Model):
    header = models.CharField(default=None, max_length=100, verbose_name="заголовок")
    description = models.TextField(default=None, max_length=300, verbose_name="описание")
    images = models.ImageField(upload_to='photos', default=None, verbose_name='Фото')
    flt = models.ForeignKey('Filters', on_delete=models.PROTECT, related_name='filters', verbose_name="фильтры",
                             default=1)

    objects = models.Manager()

    def __str__(self):
        return self.header

    class Meta:
        verbose_name = 'Вакансию'
        verbose_name_plural = 'Вакансии'


class Filters(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="фильтр")
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('filters', kwargs={'fil_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'фильтр'
        verbose_name_plural = 'Фильтры'

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль')

    class Meta:
        model = get_user_model()


class RegisterUserForm (UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput (attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput (attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput (attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
        }
        widgets = {
            'email': forms.TextInput (attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from main.models import Text_Photo, Price, Assembly, Vacancies
from django.views.decorators.cache import cache_page
from .models import Filters




@cache_page(60*15)
# Create your views here.
def page_home(request):
    txt_img = get_object_or_404 (Text_Photo, pk=1)
    carousel = Text_Photo.objects.filter (is_published=True)

    data = {
        'logo': txt_img,
        'carousel': carousel,
        'about_site': txt_img,
    }
    return render(request, 'main/index.html', context=data)


def page_price(request):
    price = Price.objects.all()
    data = {
        'price': price,
    }

    return render(request, 'main/price.html', context=data)


def page_assembly(request):
    computers = Assembly.objects.all()

    data = {
        'computers': computers,
    }

    return render(request, 'main/computers.html', context=data)


@cache_page(60*15)
def page_vacancies(request):
    vacancies = Vacancies.objects.all()
    flt = Filters.objects.all()

    data = {
        'flt': flt,
        'vacancies': vacancies,
    }

    return render(request, 'main/vacancies.html', context=data)


@login_required
def page_profile(request):
    return render(request, 'main/profile.html')


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}

    def get_success_url(self):
        return reverse_lazy('home')


def show_category(request, fil_slug):
    filters = get_object_or_404(Filters, slug=fil_slug)
    vcs = Vacancies.objects.filter(flt_id=filters.pk)
    flt = Filters.objects.all()

    data = {
        'flt': flt,
        'vacancies': vcs,
    }

    return render(request, 'main/vacancies.html', context=data)


def page_not_found(request, exception):
    return HttpResponse('<h1>Страница не найдена</h1>')

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import LoginUserForm, RegisterUserForm


# Create your views here.
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy ('users:login')

main/templates/main/computers.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'main/css/bg_video.css' %}" />
{% endblock %}

{% block content %}
        <div class="video-container">
            <video autoplay loop muted>
                <source src="{% static 'main/videos/videoplayback.mp4' %}" type="video/mp4">
            </video>
        </div>
        <div class="content_pk">
            <table>
                <tr>
                    <th>VIP</th>
                    <th>MAIN</th>
                    <th>PS</th>
                </tr>
                {% for com in computers %}
                <tr>
                    <td>{{ com.vip }}</td>
                    <td>{{ com.main }}</td>
                    <td>{{ com.ps }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}



{% block content %}
        <div class="container-fluid mt-4">
            <div class="row">
                <div class="col-lg-1">
                </div>

                <div class="col-lg-5 col-md-12">
                    <hr class="my-5">
                    <div class="row">
                        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel"
                            style="max-width: 620px;">
                            <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0"
                                    class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                                    aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                                    aria-label="Slide 3"></button>
                            </div>
                            <div class="carousel-inner">
                                {% for car in carousel %}
                                <div class="carousel-item active">
                                    <img src="{{car.image_for_carousel.url}}"  class="w-100" alt="Slide 1">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5 style="color: rgb(0, 0, 0)">PS</h5>
                                        <p style="color: rgb(0, 2, 92)">Современные ps5 и комфортный зал для</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev" type="button"
                                data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button"
                                data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>

                <div style="margin-top: 3em;" class="col-lg-5 col-md-12">
                    <hr class="my-5">
                    <div class="row px-2">
                        <div class="col-lg-12 sidebar my-4">
                            <div class="text_info">
                                <p>{{ about_site.about_site }}
                                </p>
                                <p>
                                    Мы не 'внушаем' уют - мы его дарим
                                </p>

                                <p> Спасибо что выбираете нас!</p>
                            </div>
                        </div>
{% endblock %}

{% block ftr %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>© All rights reserved 2024 </p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>More contact <br> Job<br>Our team</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
                    <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
                </div>
            </div>
        </div>
{% endblock %}

main/templates/main/price.html
{% extends 'base.html' %}


{% block content %}
<div class="content">
        <div class="container">
            <div class="center">
                <table>
                    <tr>
                        <th>ПК</th>
                        <th>PS</th>
                    </tr>
                    {% for p in price %}
                    <tr>
                        <td>{{ p.computer }}</td>
                        <td>{{ p.playstation }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block ftr %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>© All rights reserved 2024 </p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>More contact <br> Job<br>Our team</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
                    <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
                </div>
            </div>
        </div>
{% endblock %}

main/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'main/css/style_for_profile.css' %}" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<script type="text/javascript" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}


{% block content %}
<div class="my_profile">
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 py-4">
                <div class="text-center">
                    <img src="https://i.imgur.com/bDLhJiP.jpg" width="100" class="rounded-circle">
                </div>

                <div class="text-center mt-3">
                    <span class="bg-secondary p-1 px-4 rounded text-white">Pro</span>
                    <h5 class="mt-2 mb-0">{{ user.username }}</h5>
                    <span>UI/UX Designer</span>

                    <div class="px-4 mt-1">
                        <p class="fonts">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

                    </div>



                    <div class="buttons">
                        <button class="btn btn-primary px-4 ms-3"><a href="{% url 'users:logout' %}">Logaut</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}


{% block ftr %}
<div class="container-fluid">
      <div class="row">
          <div class="col-lg-4 col-md-12 footer-text text-center">
              <p>© All rights reserved 2024 </p>
          </div>
          <div class="col-lg-4 col-md-12 footer-text text-center">
              <p>More contact <br> Job<br>Our team</p>
          </div>
          <div class="col-lg-4 col-md-12 footer-text text-center">
              <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
              <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
          </div>
      </div>
</div>
{% endblock %}

main/templates/main/vacancies.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'main/css/styles_for_vacancies.css' %}" />
{% endblock %}

{% block content %}
<div class="vacancies">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-4">
                <div class="menu">
                    <ul>
                        {% for f in flt %}
                        <li><a href="{{ f.get_absolute_url }}">{{ f.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            {% for v in vacancies %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ v.images.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ v.header }}</h5>
                        <p class="card-text">
                            {{ v.description }}
                        </p>
                        <a href="#" class="btn btn-primary">Отклик</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block ftr %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>© All rights reserved 2024 </p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>More contact <br> Job<br>Our team</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
                    <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
                </div>
            </div>
        </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cyber club</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% block extra_style %} {% endblock %}
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}" />

</head>


<body>
    <div class="bg_defolt">
        <div class="main">
        <div>
            <nav class="navbar navbar-expand-lg fixed-top bg-dark navbar-dark justify-content-center custom-navbar">
                <div class="container-xl">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'home' %}"><img id='logo' src="{{logo.logo.url}}"
                                        alt="..."></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'price' %}">Цены</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'assembly' %}">Железо</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'vacancies' %}">Вакансии</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'profile' %}">Профиль</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>

        <section>
            {% block content %}
            {% endblock %}
        </section>

        <footer>
        {% block ftr %}

        {% endblock %}
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <h3 class="mb-5">Sign in</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
            <!-- Checkbox -->
                <div class="form-check d-flex justify-content-start mb-4">
                    <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                    <label class="form-check-label" for="form1Example3"> Remember password </label>
                </div>
                <div style="margin-right: 18em">
                    <p>You can to <a href="{% url 'users:register' %}">Sign Up</a></p>
                </div>
                <button data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}


{% block ftr %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>© All rights reserved 2024 </p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>More contact <br> Job<br>Our team</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
                    <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
                </div>
            </div>
        </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form class="mx-1 mx-md-4" method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                            </div>
                        </div>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}


                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg">Register</button>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}


{% block ftr %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>© All rights reserved 2024 </p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>More contact <br> Job<br>Our team</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <img class="call-anim" style="width: 120px;" src="/media/photos/tg.png" alt="...">
                    <img class="call-anim" style="width: 130px;" src="/media/photos/inst.png" alt="...">
                </div>
            </div>
        </div>
{% endblock %}